<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TestFB" Id="{d4512a1f-eebd-4ae3-84c4-0871c2262757}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TestFB// IMPLEMENTS ITestProps
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>